### ISSUE TITLE
Filter buttons disappear as cards load

### ISSUE THREAD

**Issue by bobbruno** [gmq/trello-filter#6]
I cannot use the extension anymore. It used to have a problem that the filter buttons would not show until I reloaded the page, but now they don't stay there even after reloading.

They briefly show while the page is loading, but as it finishes, the filters are gone. Maybe some new javascript code from Trello is deleting the buttons.

**Comment by gmq** [comment]
I'd love to help you but I can't replicate the problem, maybe it's some other extension?

**Comment by falmarkspeter** [comment]
I have the same problem as@bobbruno.
I've triad disabling my other extensions. Doesn't change anything.

**Comment by falmarkspeter** [comment]
Clearing Cookies and Cache seamed to fix this issue for me,
